development:
  adapter: mysql
  encoding: utf8
  database: crm_rails_development
  username: root
  password: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: crm_rails_test
  username: root
  password: root
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: crm_rails_production
  username: root
  password: 
  socket: /tmp/mysql.sock
